### ISSUE TITLE
creating BoxedAnnotation objects is brittle

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#510]
BoxedAnnotation objects are fairly brittle. For example BoxedAnnotation objects require the following columns in the underlying dataframe: [ "annotation", "start_time", "end_time", "low_f", "high_f"]

When reading over a large number of Raven/selection table files, if there are typos, differences in the names of the columns or some columns missing BoxedAnnotation.from_raven_file will throw an error. This means I have sometimes found myself reading in the selection table files as dataframes. However then I can't use the handy functions built in as methods for BoxedAnnotation objects (e.g. one_hot_labels_like).

I think we should make BoxedAnnotation objects more flexible, or rewrite the helper functions like one_hot_labels_like so that they can be applied to other dataframe objects.

**Comment by sammlapp** [comment]
Flexibility would be good, but I think we should continue to use BoxedAnnotations objects with dedicated methods so that the information in the object has some enforced consistency. The columns [ "annotation", "start_time", "end_time", "low_f", "high_f"] are created by BoxedAnnotation.from_raven - so do you think that's the method that is too brittle? Other than the name of the annotation column, which is an argument of from_raven, I thought all the other column names were consistent within Raven Pro/Lite. Any ideas on how to make it less brittle?

**Comment by rhine3** [comment]
One area of brittleness that I'd like to improve is that we currently can't natively load selection tables without an annotation column. Some people who are just annotating a single species are not going to use a column of labels (e.g. @carlybatist).

So, for example, a user should be able to load a selection table without an "annotations" column using:
```
annotations = BoxedAnnotations.from_raven_file(annotation_file, annotation_column=None)
```

This would also make the `BoxedAnnotations` class more flexible such that, if you find there are typos in the names of annotation columns, you could load them with `annotation_column=None` then use a for-loop to rename the annotation columns for consistency.

Along with that, when splitting `BoxedAnnotations` using `one_hot_labels_like()`, the behavior of `classes=None` is unintuitive -- it would seem to suggest that there are no classes, but instead, the behavior is that it uses all classes. It also means, again, that if you have a selection table where there are no annotations, this function can't be used without hacky workarounds (see footnote)

I think we should change the API so that:
* By default, if the argument `classes` is not provided, then it uses all of the classes (currently `classes=None` provokes this behavior). This could be `classes=True`.
* If the user gives the argument `classes=None`, then the function should assume that there is only a single class, and return a labels_df with either a single present/absent column.
* If the user gives a list of classes as an argument `classes = ['list','of', 'classes']` then the function should behave as it currently does.

---
Footnote - a workaround that Carly and I just came up with was to use `annotation_column="Selection"`, which means the selections have the "classes" [1, 2, 3, ...] representing the numerical index of the selection that Raven gives the selection by default. Then, when using `one_hot_labels_like()`, the labels dataframe had columns `[1, 2, 3, ...]`, which we summed (`labels_df.sum(axis=1)`) to create a binary labels column.

**Comment by sammlapp** [comment]
I think that the proposed API for classes is a bit too complex. While classes=None may be unintuitive for all classes, it is pretty standard in python to provide None for some default behavior. Having three different data types possible for an argument is messy, particularly when one is Boolean (because a lot of things evaluate to True in python). Open to other possibilities.

**Comment by rhine3** [comment]
**Alternative 1**
We could check the type of the argument with ```if type(classes) == bool:``` and accept the following arguments: `classes=True`, `classes=False`, and `classes=['list','here']` - though not as interpretable

**Alternative 2**
We could change the name of that parameter so that it's more interpretable:
* `class_subset=None` (default value) uses all classes
* `class_subset=['binary']` or `class_subset=[]` allows for use of no annotation
* `class_subset=['list','of','classes']` uses only those classes

**Alternative 3**
We could simply handle no-annotation files by *giving* them an annotation column when loading in `BoxedAnnotations`. 

I would suggest that when loading a BoxedAnnotations file, the argument `annotation_column=None` indicates there is no annotation column, as suggested above. When this argument is None, `BoxedAnnotations.from_raven_file` could require a second argument, `class_name`, where the user passes the desired name of the class. Then, OpenSoundscape could automatically *add* an annotation column (let's say it's called "annotation") where all the values are `class_name`. From there, the splitting functionality works as written.

Example:
```
annotations = BoxedAnnotations.from_raven_file(annotation_file, annotation_column=None, class_name="GWWA")
```
Would produce a `BoxedAnnotations` instance with a DataFrame that has a column called "annotation," the value of which is "GWWA" for every row.

In this case, I still think we should change the name of `classes` in the splitting functionality to something like `class_subset`, so that the `None` argument is more linguistically interpretable to a new user.

**Comment by sammlapp** [comment]
I like Alternative 2 with `class_subset={None, [],['list','of','classes']}`

**Comment by sammlapp** [comment]
Noting that since this will be a breaking API change, which we typically reserve for 0.x minor releases, we should make the breaking change clear in the release notes and documentation
