### ISSUE TITLE
Metadata parsing is not bypassed by metadata=False in Audio.from_file

### ISSUE THREAD

**Issue by carlybatist** [kitzeslab/opensoundscape#520]
Anytime I do anything with an Audiomoth file I get this warning message per file -  

/anaconda/envs/cv4e/lib/python3.7/site-packages/opensoundscape/audio.py:180: UserWarning: This seems to be an AudioMoth file, but parse_audiomoth_metadata() raised: list index out of range
  "This seems to be an AudioMoth file, "

...and I have thousands of files so I keep getting these warning messages show up every time and it's really annoying and also hard to read the output of the file running. I have tried:
import warnings
warnings.filterwarnings("ignore") 

but it doesn't work, the warnings still appear. 
I also tried doing this: python -W ignore foo.py 
but it also doesn't work, the warnings still appear. 

Thoughts on workarounds?

**Comment by sammlapp** [comment]
If you use `metadata=False` in Audio.from_file, it will not attempt to parse the metadata and will not raise a Warning. 

It would be useful to know which AudioMoth firmware you are using so that we can update the metadata parsing to be compatible with that firmware. The AudioMoth often changes the format of metadata with new firmware releases, which breaks the metadata parsing.

**Comment by carlybatist** [comment]
These files were Audiomoth firmware 1.7

**Comment by carlybatist** [comment]
Also I tried the metadata=False in Audio.from_file and it didn't work - still got the warning messages.

**Comment by sammlapp** [comment]
Good catch, the code is not properly using the `metadata=False` option. I'm going to edit the issue's original title to reflect this.
