### ISSUE TITLE
Working with only positive annotations?

### ISSUE THREAD

**Issue by carlybatist** [kitzeslab/opensoundscape#521]
I only have annotated the files that have calls of interest in them (positive class), which is a small subset of the total files. Is there a way to have the code understand that whatever doesn't have an annotation is a negative class? I tried to create dummy txt files for each negative class file through Python but I don't think it's working correctly because later on in the batch split_and_save for loop  (as in line 24 here: http://opensoundscape.org/en/latest/tutorials/annotation_tutorial.html), the one-hot encoded labels aren't working. The resulting CSV has a bunch of files that don't have any label (both positive and negative class columns show '0'). And it's getting tripped up by some files that I'm currently forcing it to skip just to get the code to run, but those files are the exact same format as all the other ones so I can't understand why it thinks they're different.

**Comment by carlybatist** [comment]
Basically the line of thinking described in the koogu package here - https://shyamblast.github.io/Koogu/en/stable/quickstart.html. Koogu won't install in my environment so I'm not currently able to actually try out that function shown, but basically is there an Open Soundscape version of this concept?

<img width="753" alt="Screen Shot 2022-08-13 at 8 53 23 AM" src="https://user-images.githubusercontent.com/46716228/184501502-fe522dbf-ea8d-4f2a-80c8-ee80a65c100d.png">

**Comment by sammlapp** [comment]
You can accomplish this without creating any additional labels, as described in the [annotation tutorial](http://opensoundscape.org/en/latest/tutorials/annotation_tutorial.html).

For instance, let's assume you have labeled your files using Raven and load those files into BoxedAnnotations objects in opensoundscape with the `annotations` module. For instance:
```
annotations = BoxedAnnotations.from_raven_file('raven_annotations.txt',annotation_column='Species')
```

Now, let's say you choose to create one-hot (0 and 1) labels for fixed-length clips:

```
labels_df = annotations.one_hot_clip_labels(
    full_duration=60,
    clip_duration=5,
    clip_overlap=0,
    classes=['species1'],
    min_label_overlap=0.25,
)
```

The dataframe `labels_df` contains a row for each 5 second clip, with a 1 in the `species1` column if it contains a raven annotation and a 0 if not. Filtering this dataframe by the rows with 1 and 0 will provide sets of clips with and without annotations, respectively. 

Please follow the detailed [annotation tutorial notebook](http://opensoundscape.org/en/latest/tutorials/annotation_tutorial.html) for a more detailed description of this process.


If, alternatively, you have a set of _files_ with a single label (present/absent) each rather than raven annotations for a set of files, you should simply create a table of files and their 0/1 labels.

**Comment by rhine3** [comment]
FYI I think Carly's issue here was the same issue already described in #510 - OpenSoundscape doesn't natively create BoxedAnnotation objects without an annotation column. There's a workaround described in that thread, and the OPSO dev team is currently working on adding that feature.
