### ISSUE TITLE
Inconsistent use of the term 'model'

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#552]
It is confusing how we use the term model. In our tutorials we show instantiating a model by e.g.
```
from opensoundscape.torch.models.cnn import CNN
model = CNN('resnet18',classes=classes,sample_duration=2.0,single_target=True)
```

But sometimes in the codebase we use `model` to refer to something else. e.g. modify_resnet in opensoundscape.torch.architectures.cnn_architectures takes a `model` argument, which would actually be `model.network` using the object instantiated above. We should decide on consistent terminology.
```
def modify_resnet(model, num_classes, num_channels)
"""modify input and output shape of a resnet architecture"""
....
```

**Comment by sammlapp** [comment]
I wanted to use the term "model" for opensoundscape.torch.models.cnn.CNN and similar, ie OpenSoundscape's classes, rather than CNN.network which I refer to as "architecture" as much as possible (so in your above example, model should be 'architecture'). However, this conflicts with PyTorch's use of the word model for the objects we call "architectures", so you could argue that we should follow that convention and call opso classes like CNN something else.

**Comment by sammlapp** [comment]
Let's use "model" for opso CNN class and similar, and use "architecture" for pytorch resnet18 and similar.
