### ISSUE TITLE
[Dependency] `resampy`

### ISSUE THREAD

**Issue by jatinkhilnani** [kitzeslab/opensoundscape#674]
OpSo v8.0: `Audio.resample(sample_rate)` throws `ModuleNotFoundError: No module named 'resampy'`

**Comment by sammlapp** [comment]
rather than add a new dependency, we'll change the default resample method of Audio.resample to "soxr_hq", following Librosa's change in v0.10.1

(As of v0.10.1 librosa depends on resampy if using "kaiser_fast" resampling method, the previous default method, and does not install resampy as a dependency)
