### ISSUE TITLE
consider changing detections format in localization branch 

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#700]
could be formatted more like a raven selection table (class name as a value in a column, one row per detection) as opposed to classes as columns. Would allow specifying frequency bounds on a per-detection basis.

**Comment by louisfh** [comment]
Our current format for detections closely matches the output of our classifiers, so I think we should keep it. 

However, one of the problems with our implementation is that we only cross-correlate identical time-bins across multiple recordings, at a specific time-resolution. 
e.g. assuming detections looks like below:
|file | start_time | end_time | species_1 |
|----|------------|----------|-----------|
1.mp3 | 0 | 3 | 1 |
2.mp3 | 0 | 3 | 1 |
3.mp3 | 0 | 3 | 1|
4.mp3 | 3 | 6 | 1 |

We will not use `4.mp3`, because it is in the wrong discrete time-bin, even though it's plausible it could be within `max_delay` of the other files. This is a bigger issue if we have a classifier that uses short time-bins and outputs detections at fine time-resolution. If we used a detections format like you're suggesting, that specified start and end times, we could be cleverer about how we do this.

**Comment by sammlapp** [comment]
If you have one audio file annotated and want to assume that the annotation applies to other nearby recorders, you can simply create an annotation row for each annotation, with the start and end time of the annotation. This works in the current implementation.

**Comment by sammlapp** [comment]
should I close this @louisfh ?

**Comment by louisfh** [comment]
Yes I vote for closing this. 

As you point out, if you have a single ARU that has raven annotations, you could simply duplicate these annotations across nearby ARUs and use the pipeline as is. The problem would be if a user has separate raven annotations for each ARU, and wants to use these for localization. Right now they would have to turn them into a dataframe of detections on discrete time-windows, like the output of our CNNs (see earlier comment above for the format of this detections dataframe). This isn't perfect, because it would make more sense to just cross-correlate the audio of the annotation boxes rather than the discrete time-windows. But I don't think its worth the overhead to write a different implementation right now, given we don't know anyone who makes raven annotations for each ARU?

**Comment by sammlapp** [comment]
just noting that this could come up when we localize wolves at distances of km
