### ISSUE TITLE
Consider adding/changing SpatialEvent attributes to contain a datetime timestamp 

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#761]
SpatialEvent objects have the attributes:
`start_time`, `duration` and `receiver_files`.

It might be convenient to either change start_time to a datetime timestamp, or add another attribute that is start_time_ts. This would save having to do things like keep SpatialEvents in a dictionary of form {date1: [SpatialEvent, SpatialEvent...], date2:[SpatialEvent, SpatialEvent...]}.

**Comment by sammlapp** [comment]
I have an implementation of this from last year's localization analysis. I can open a branch with the additions. There are some factors left to consider for an opso API because my code assumes the start timestamp of the audio can be parsed from the metadata, eg when we are using AudioMoth files. Should probably modify so that user provides the start timestamp for each row of the detection table.

**Comment by sammlapp** [comment]
@louisfh when you get a chance, take a look at the branch `loca_timestamp` for a first pass at an implementation
