### ISSUE TITLE
Slow CNN Training and Inference in 0.9.0 onwards

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#774]
Noticed by a couple of people. It is not related to GPU vs CPU usage. However inspecting GPU usage shows that it is staying at 0% and infrequently spiking. This suggests it is a preprocessing issue happening on the CPU which is slowing things down.

This may be because of the `AudioSample` class we introduced in 0.9.0

**Comment by LeonardoViotti** [comment]
Having this issue with `librosa==0.10.0.post2`, but this is the same version I had in the previous environment in which I think wasn't having the slow training issue.

**Comment by sammlapp** [comment]
@louisfh or @LeonardoViotti do you think there is actually an issue in the code base (or dependencies) causing a slow-down, or did it turn out to be something related to the users' hardware/system? (Also if it doesn't happen with opso 0.10.1 we will close the issue since we don't continue support for previous 0.x releases)
