### ISSUE TITLE
should Spectrogram values only be clipped to .decibel_limits during .plot() and .to_image()? 

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#793]
Rather than clipping the values of a Spectrogram (`.spectrogram` property) to [min,max] range specified by .decibel_limits, maybe the original values should be retained, and .decibel_limits should only be used to clip values and set ranges during plotting or image creation. credit to @m1alksne for this insight

**Comment by rhine3** [comment]
Yes, I like this! Though I'm wondering if it could be deceiving if decibel_limits were still an argument to `Spectrogram()`, because if you access the `.spectrogram` directly you might expect it to have the decibel limits applied. What if these were arguments to the methods for plotting or creating images?

**Comment by sammlapp** [comment]
yep I agree that that's a good idea. The plot and to_image functions should also give helpful warnings if the values of the spectrogram do not fall in the values of the default or user-specified bandpass range
