### ISSUE TITLE
AssertionError: Train and validation datasets must have same classes and class order as model object.

### ISSUE THREAD

**Issue by louisfh** [kitzeslab/opensoundscape#833]
This is an annoying error raised when you try and train a model, but the order of your train_df columns don't match the order of the classes in the self.classes of the model.

Can't we just assert that `set(self.classes) = set(train_df.columns)`?

**Comment by sammlapp** [comment]
the class list is usually treated as an ordered list, not just an unordered set. One reason for this is that PyTorch models receive and return matrices (tensors), rather than dataframes or something. So when you get a tensor out of the model, you need to know which outputs correspond to which classes. 

Inside .train(), we _could_ re-order the columns of the passed train df internally, or re-order the outputs to match the order of train df columns, or just let the two dfs have different orders of columns, but I don't like any of those solutions. I think when you do something like `preds_df = cnn.predict(val_df)`, the `.values` of each df should correspond directly to each other (as they do now).

Perhaps we can add a message to the warning like "consider using `train_df=train_df[cnn.classes]` or `cnn.classes=train_df.columns` before training."
