### ISSUE TITLE
to_tensor action in pipeline does not expose all arguments of Spectrogram.to_image

### ISSUE THREAD

**Issue by sammlapp** [kitzeslab/opensoundscape#881]
For instance, cannot pass range parameger (formerly decibel_range of spectrogram.from_audio  / `to_spec` action) 

(raised by @canihaveabravo in #875 )

A workaround, and potential solution in the code base for updated SpectrogramToTensor class:

```python
from opensoundscape.preprocess.actions import Action
from opensoundscape import Spectrogram
class SpectrogramToTensor(Action):
    """Action to create Tesnsor of desired shape from Spectrogram

    calls .to_image on sample.data, which should be type Spectrogram
    
    **kwargs are passed to Spectrogram.to_image()
    
    """
    def __init__(
        self,
        fn=Spectrogram.to_image,
        is_augmentation=False,
        **kwargs
    ):
        kwargs.update(dict(return_type='torch')) #return a tensor, not PIL.Image
        super(SpectrogramToTensor, self).__init__(fn,is_augmentation,**kwargs)
    def go(self, sample, **kwargs):
        """converts sample.data from Spectrogram to Tensor"""
        # sample.data must be Spectrogram object
        # sample should have attributes: height, width, channels
        # use info from sample for desired shape and n channels
        kwargs.update(
            shape=[sample.height, sample.width],
            channels=sample.channels
        )
        sample.data = self.action_fn(sample.data, **dict(self.params, **kwargs))

# generate an instance of this action with the desired decibel range
my_action = SpectrogramToTensor(range=[-120,-30])

# replace to_tensor action with this action
pre.pipeline.to_tensor = my_action
```

**Comment by canihaveabravo** [comment]
HI Samm,

Thank you for your help with the decibel_imits issue I experienced on the Spectrogram preprocessor. I am now having difficulty training my model in the new OpSo version. My code below:

model.logging_level = 2 # request lots of logged content
model.log_file = './multispecies_model_train_3/training_log_20102023.txt' #specify a file to log output to
Path(model.log_file).parent.mkdir(parents=True,exist_ok=True) #make the folder ./

model.verbose = 1 #don't print anything to the screen during training

#learning rate schedule
model.lr_cooling_factor = 0.3
model.lr_update_interval = 4

#Regularization weight decay
model.optimizer_params['weight_decay']=0.001

# Train the model on the full training set and validate on the validation set. Save the model to directory.
model.train(
    balanced_train_df,
    #train_df,
    valid_df,
    epochs= 1,
    batch_size= 64,
    log_interval = 5,
    num_workers= 4, # if multiple processors are available utilise them to speed up training
    #wandb_session = wandb_session,
    save_interval= 10,
    save_path= checkpoint_folder #location to save checkpoints
)

#Let Wandb know that we finished training successfully
wandb.unwatch(model.network)
wandb.finish()

Throws us the following error:

raining Epoch 0
0%
0/46 [00:42<?, ?it/s]
<frozen importlib._bootstrap>:1047: ImportWarning: ImportHookFinder.find_spec() not found; falling back to find_module()
---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
File c:\Users\lscala\AppData\Local\anaconda3\envs\opensoundscape\Lib\site-packages\torch\utils\data\dataloader.py:1132<file:///C:/Users/lscala/AppData/Local/anaconda3/envs/opensoundscape/Lib/site-packages/torch/utils/data/dataloader.py:1132>, in _MultiProcessingDataLoaderIter._try_get_data(self, timeout)
   1131 try:
-> 1132     data = self._data_queue.get(timeout=timeout)
   1133     return (True, data)

File c:\Users\lscala\AppData\Local\anaconda3\envs\opensoundscape\Lib\multiprocessing\queues.py:114<file:///C:/Users/lscala/AppData/Local/anaconda3/envs/opensoundscape/Lib/multiprocessing/queues.py:114>, in Queue.get(self, block, timeout)
    113     if not self._poll(timeout):
--> 114         raise Empty
    115 elif not self._poll():

Empty:

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
c:\Users\lscala\Python_learning\multispecies_trial_chris.ipynb<file:///C:/Users/lscala/Python_learning/multispecies_trial_chris.ipynb> Cell 19 line 1
     12<vscode-notebook-cell://c%3A/Users/lscala/Python_learning/multispecies_trial_chris.ipynb#X22sZmlsZQ%3D%3D?line=11> model.optimizer_params['weight_decay']=0.001
     14<vscode-notebook-cell://c%3A/Users/lscala/Python_learning/multispecies_trial_chris.ipynb#X22sZmlsZQ%3D%3D?line=13> # Train the model on the full training set and validate on the validation set. Save the model to directory.
---> 15<vscode-notebook-cell://c%3A/Users/lscala/Python_learning/multispecies_trial_chris.ipynb#X22sZmlsZQ%3D%3D?line=14> model.train(
     16<vscode-notebook-cell://c%3A/Users/lscala/Python_learning/multispecies_trial_chris.ipynb#X22sZmlsZQ%3D%3D?line=15>     balanced_train_df,
     17<vscode-notebook-cell://c%3A/Users/lscala/Python_learning/multispecies_trial_chris.ipynb#X22sZmlsZQ%3D%3D?line=16>     #train_df,
     18<vscode-notebook-cell://c%3A/Users/lscala/Python_learning/multispecies_trial_chris.ipynb#X22sZmlsZQ%3D%3D?line=17>     valid_df,
     19<vscode-notebook-cell://c%3A/Users/lscala/Python_learning/multispecies_trial_chris.ipynb#X22sZmlsZQ%3D%3D?line=18>     epochs= 1,
...
-> 1145     raise RuntimeError(f'DataLoader worker (pid(s) {pids_str}) exited unexpectedly') from e
   1146 if isinstance(e, queue.Empty):
   1147     return (False, None)

RuntimeError: DataLoader worker (pid(s) 18868, 18184, 19292, 20324) exited unexpectedly
Output is truncated. View as a scrollable element<command:cellOutput.enableScrolling?c9cfdb8a-3cdc-4a1f-a618-229ff125be40> or open in a text editor<command:workbench.action.openLargeOutput?c9cfdb8a-3cdc-4a1f-a618-229ff125be40>. Adjust cell output settings<command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D>...


You’ll notice I have also commented out the WandB_session = WandBsession argument, as this also throws up an error related to missing samplez / training samples dir.

I have tried various tweaks to prevent the RuntimeErrorDataLoader error but without success. Have you come across this problem before?

Thanks very much,
Lorenzo



Lorenzo Scala
Senior Marine Scientist
Seiche Ltd
T:
 +44(0)1409 404050
E: ***@***.***
W: https://www.seiche.com
Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
 Seiche Ltd is registered in England & Wales. Registered number: 1468514. Registered Office: Bradworthy Industrial Estate, Langdon Road, Bradworthy, Holsworthy, Devon, EX22 7SF, United Kingdom
 
 The information contained in this e-mail transmission, and any documents, files or previous e-mail messages attached to it, is privileged and confidential, and solely intended for the use of the individual(s) to whom it is addressed.  If you are not the intended recipient or a person responsible for delivering it to the intended recipient you should not read, copy, distribute or otherwise use the information, and you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is strictly prohibited.  If you have received this message in error, please notify sender immediately and delete this e-mail and attached documents.
 
From: sammlapp ***@***.***>
Sent: Thursday, October 19, 2023 8:38 PM
To: kitzeslab/opensoundscape ***@***.***>
Cc: Lorenzo Scala ***@***.***>; Mention ***@***.***>
Subject: [kitzeslab/opensoundscape] to_tensor action in pipeline does not expose all arguments of Spectrogram.to_image (Issue #881)


CAUTION: This email originated from outside of SWTG.

For instance, cannot pass range parameger (formerly decibel_range of spectrogram.from_audio / to_spec action)

(raised by @canihaveabravo<https://github.com/canihaveabravo> in #875<https://github.com/kitzeslab/opensoundscape/discussions/875> )

Implement more generic SpectrogramToTensor action like this:

from opensoundscape.preprocess.actions import Action

from opensoundscape import Spectrogram

class SpectrogramToTensor(Action):

    """Action to create Tesnsor of desired shape from Spectrogram



    calls .to_image on sample.data, which should be type Spectrogram



    **kwargs are passed to Spectrogram.to_image()



    """

    def __init__(

        self,

        fn=Spectrogram.to_image,

        is_augmentation=False,

        **kwargs

    ):

        kwargs.update(dict(return_type='torch')) #return a tensor, not PIL.Image

        super(SpectrogramToTensor, self).__init__(fn,is_augmentation,**kwargs)

    def go(self, sample, **kwargs):

        """converts sample.data from Spectrogram to Tensor"""

        # sample.data must be Spectrogram object

        # sample should have attributes: height, width, channels

        # use info from sample for desired shape and n channels

        kwargs.update(

            shape=[sample.height, sample.width],

            channels=sample.channels

        )

        sample.data = self.action_fn(sample.data, **dict(self.params, **kwargs))



# generate an instance of this action with the desired decibel range

my_action = SpectrogramToTensor(range=[-120,-30])



# replace to_tensor action with this action

pre.pipeline.to_tensor = my_action

**Comment by sammlapp** [comment]
> HI Samm, ...
@lorenzo I will open a separate thread in discussions since the question is unrelated to issue #881 
https://github.com/kitzeslab/opensoundscape/discussions/893
