### ISSUE TITLE
decibel_limits disappeared from preprocessor pipeline

### ISSUE THREAD

**Issue by fascimare** [kitzeslab/opensoundscape#918]
On the website, the params of preprocessor.pipeline.to_spec contain decibel limits that can be adjusted. I recently (two weeks ago) downloaded opensoundscape, but cannot find this line in my params file. This also means I cannot adjust it, and all my spectrograms turn out either white or black.

**Comment by sammlapp** [comment]
Hi, in opensoundscape v0.10.0 this adjustment knob moved from to_spec to to_tensor action (because the decibel limits are now applied not when creating the spectrogram but when converting it to a PyTorch tensor). It looks like the preprocessing tutorial notebook was not updated to reflect this change, apologies about that. We’ll make that change soon. 

To adjust the decibel limits with opensoundscape>=0.10.0 use

`preprocessor.pipeline.to_tensor.set(range=(-150,-50))`

note that the param is called range.

**Comment by sammlapp** [comment]
closing since #922 requests the change in the documentation
