### ISSUE TITLE
Some attributes of SpatialEvent are vague

### ISSUE THREAD

**Issue by rhine3** [kitzeslab/opensoundscape#932]
The `event.tdoas`, `event.locs`, and `event.cc_maxs` contain values for all receivers. 

But since any receiver with a cc_max less than the `event.cc_threshold` is excluded from being used during localization, it can be tricky to correctly reference just the receivers used for localization.

E.g. if you want to find the TDOAs just for the receivers used, you'd do `event.tdoas[event.cc_maxs > event.cc_threshold]`

https://github.com/kitzeslab/opensoundscape/blob/cf77a561f8b7f372b930c928b07349af958490a8/opensoundscape/localization.py#L201

Sam's suggestions was to put data about the array into a dataframe that you could query more easily, e.g. a row for each file, a 1/0 for whether or not each file was used in localization, etc.

**Comment by sammlapp** [comment]
The trick is that we’d like to be able to convert the event into (a) a pd.Series to make a single dataframe of a bunch of events, and (b) json so that we can load or save events to disk. 

If we use a df internal to the event, could make json by turning each column of df into a list. 

Alternative to making a df with one event per row, it may be better to just keep a list of events. Filtering or summarizing them would require iterating the list. Or use pd.Series if we want to use .apply()

**Comment by sammlapp** [comment]
I think the solution to this is to create @properties for cc_maxs used, etc, that filter to only those used like event.tdoas[event.cc_maxs > event.cc_threshold]

**Comment by sammlapp** [comment]
a better solution might be to have separate classes: 
- spatial events, which have raw unlocalized data and localization methods, and 
- (immutable/static) event location estimates, which are produced by .localize() and contain the location estimate + parameters used
