### ISSUE TITLE
Error reloading EfficientNet model in different script

### ISSUE THREAD

**Issue by paulpeyret-biophonia** [kitzeslab/opensoundscape#998]
Hi,

Thanks for this great module! 🤗 

I want to share with you a strange error that I found while training an efficientnet model.

### Error description
I am facing a module import error when I try to reload a trained a model with efficientnet-b0 architecture.

### Configuration 
Windows 11
OPSO v0.10.1
torch v2.2.2

### Steps to reproduce:
1. Train model with efficientnet-b0 or efficientnet-b4 in a notebook
2. Make sure the model is saved somewhere
3. In a **different notebook** (same environment), launch `torch.load(path_to_model)`

It raises the following Error: ModuleNotFoundError: No module named 'PyTorch'

_Note: The strange thing is that reloading the model file in the same notebook works fine, but if you load it from another notebook it returns an error._

### Possible cause
It seems like during the loading of the model, it tries to access the following module that does not exist.
'PyTorch.Classification.ConvNets.image_classification.models.efficientnet'

I tried to do the same thing with "resnet-18" architecture and it works fine.

Maybe torch module was aliased PyTorch somewhere in torch hub for this specific model architecture ?

Please let me know if you are able to reproduce this behavior.
Many thanks.

**Comment by sammlapp** [comment]
Thanks @paulpeyret-biophonia , I did reproduce this error in the same way you described: creating a model and loading it in a new notebook with load_model produces ModuleNotFoundError for "PyTorch".

The reason for this is that when we initialize an efficientnet in OpenSoundscape, we are pulling from torch hub for the architecture:

https://github.com/kitzeslab/opensoundscape/blob/3affc8bd771f5bb3ecaf2afd7305f456c53e09d6/opensoundscape/ml/cnn_architectures.py#L495

But when we re-load, we simply try to load the pickled model object with torch.load(), and the class definition is not available since the class's definition exists in the repo "NVIDIA/DeepLearningExamples:torchhub" rather than in OpenSoundscape. 

(By contrast, architectures like resnet are accessed from the locally-available module such as `torchvision.models.resnet18`)

I hadn't considered this issue with re-loading models when using torch.hub to generate the initial architecture. I'm thinking about the best solution.

**Comment by sammlapp** [comment]
The solution should be to only use classes from within dependencies to build architectures. EfficientNet architectures are now available in PyTorch so this isn't a problem for our currently supported architecture list. 

As a workaround to your issue with previously trained models, you can clone the [DeepLearningExamples:torchhub repo:branch](https://github.com/NVIDIA/DeepLearningExamples/tree/torchhub) used to create the efficientnet and import the class definition for efficientnet_b0 (`from PyTorch.Classification.ConvNets.image_classification.models import efficientnet_b0 as nvidia_efficientnet_b0`) before calling `load_model`.

**Comment by sammlapp** [comment]
Annoyingly, the pytorch implementation is not going to match key-for-key with the previously used architecture. When we update to native pytorch architectures, loading models created in previous versions will require specifically importing and using the class from [DeepLearningExamples:torchhub repo:branch](https://github.com/NVIDIA/DeepLearningExamples/tree/torchhub) eg `from PyTorch.Classification.ConvNets.image_classification.models import efficientnet_b0 as nvidia_efficientnet_b0`
